//
//  RoleMiddleware.swift
//  RecipeBackend
//
//  Created by Jenna Bunescu on 11/15/25.
//

// SOURCE CODE: GENERATED BY CHATGPT

import Vapor
import JWT


struct RoleMiddleware: AsyncMiddleware {
    let allowedRoles: [String]

    func respond(to req: Request, chainingTo next: any AsyncResponder) async throws -> Response {
        let payload = try req.auth.require(UserPayload.self)
        
        // Check if the JWT audience contains at least one of the allowed roles
        if !payload.aud.value.contains(where: { allowedRoles.contains($0) }) {
            throw Abort(.forbidden, reason: "Insufficient permissions")
        }
        
        return try await next.respond(to: req)
    }
}
